"""The license firewall.

Scans every file that could plausibly become training data and asserts that no
row was generated by a model whose terms forbid it.

The failure mode this prevents is mundane and fatal: you distil a frontier
model's trajectories into an open adapter, publish the adapter, and discover
that the provider's acceptable use policy barred exactly that. Anthropic's is
the strictest of the three, barring the use of inputs and outputs to train an
AI model with no competing-use qualifier at all.

Scanned by default: ``data/train/**/*.jsonl`` and ``data/sft/**/*.jsonl``.
Everything under ``eval/`` is explicitly *not* scanned, because evaluation is
inference, not training, and frontier models belong there.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from toolsmith.config import REPO_ROOT, Registry, load_registry

#: Directories whose contents may reach a trainer.
TRAINING_GLOBS: tuple[str, ...] = (
    "data/train/**/*.jsonl",
    "data/sft/**/*.jsonl",
    "data/distill/**/*.jsonl",
    "optimize/artifacts/**/*.jsonl",
)

#: Directories that are inference-only and therefore exempt.
EXEMPT_PREFIXES: tuple[str, ...] = ("eval/", "docs/", "tests/")


@dataclass
class Violation:
    path: str
    line: int
    generator_model: str
    reason: str


@dataclass
class FirewallReport:
    files_scanned: int = 0
    rows_scanned: int = 0
    rows_without_provenance: int = 0
    violations: list[Violation] = field(default_factory=list)
    generators_seen: dict[str, int] = field(default_factory=dict)

    @property
    def clean(self) -> bool:
        return not self.violations and self.rows_without_provenance == 0

    def to_dict(self) -> dict[str, object]:
        return {
            "files_scanned": self.files_scanned,
            "rows_scanned": self.rows_scanned,
            "rows_without_provenance": self.rows_without_provenance,
            "generators_seen": dict(sorted(self.generators_seen.items())),
            "violations": [v.__dict__ for v in self.violations],
            "clean": self.clean,
        }


def _is_exempt(path: Path, root: Path) -> bool:
    rel = path.relative_to(root).as_posix()
    return any(rel.startswith(prefix) for prefix in EXEMPT_PREFIXES)


def scan(
    root: Path | None = None,
    registry: Registry | None = None,
    globs: tuple[str, ...] = TRAINING_GLOBS,
) -> FirewallReport:
    root = root or REPO_ROOT
    registry = registry or load_registry()
    report = FirewallReport()

    paths = sorted({p for pattern in globs for p in root.glob(pattern) if p.is_file()})
    for path in paths:
        if _is_exempt(path, root):
            continue
        report.files_scanned += 1
        for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            line = raw.strip()
            if not line:
                continue
            report.rows_scanned += 1
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                report.violations.append(
                    Violation(str(path.relative_to(root)), lineno, "?", "row is not valid JSON")
                )
                continue

            prov = row.get("provenance")
            if not isinstance(prov, dict):
                report.rows_without_provenance += 1
                continue

            generator = prov.get("generator_model")
            if generator is None:
                continue  # oracle_program, world_seed and human_label rows
            report.generators_seen[generator] = report.generators_seen.get(generator, 0) + 1

            spec = registry.models.get(generator)
            if spec is None:
                report.violations.append(
                    Violation(
                        str(path.relative_to(root)),
                        lineno,
                        generator,
                        "generator_model is not a key in configs/models.yaml, so its "
                        "licence cannot be checked",
                    )
                )
                continue
            if spec.training_data_use == "forbidden":
                report.violations.append(
                    Violation(
                        str(path.relative_to(root)),
                        lineno,
                        generator,
                        f"{spec.provider} forbids using outputs as training data "
                        f"(training_data_use: forbidden)",
                    )
                )
            elif spec.training_data_use == "competing_use_only":
                # Allowed, but recorded, because "allowed for now" is a fact with a date on it.
                report.generators_seen.setdefault(f"{generator} (competing-use caveat)", 0)

    return report


def allowed_generators(registry: Registry | None = None) -> list[str]:
    """The models whose outputs may legally become training data."""
    registry = registry or load_registry()
    return sorted(
        key for key, spec in registry.models.items() if spec.training_data_use != "forbidden"
    )
