"""Where every row of data came from, recorded on the row itself.

The rule this enforces is simple and absolute: training data may originate only
from (a) oracle programs written in this repository, (b) self-hosted
Apache-2.0 or MIT weights, or (c) providers whose terms permit it, which today
means Groq, Mistral and Together. Anthropic, OpenAI and Google are
inference-only. They appear in the evaluation matrix and as escalation targets,
and never in a file that a trainer reads.

That is not a promise in a README. It is a pydantic field that the license
firewall reads, and a CI job that fails the build.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

SourceType = Literal[
    "oracle_program",  # deterministic code in this repository
    "world_seed",  # generated by a seeded RNG from stdlib wordlists
    "human_label",  # written by a person, in the review UI
    "model_output",  # produced by a model; licence checked against the registry
    "derived",  # computed from other rows; inherits the strictest parent
]


class Provenance(BaseModel):
    """Attached to every dataset row, trajectory and judgment."""

    model_config = ConfigDict(extra="forbid")

    source_type: SourceType
    generator_model: str | None = None
    """Registry key, not a vendor string. The firewall resolves it against
    ``configs/models.yaml`` and reads ``training_data_use``."""

    generator_version: str = ""
    prompt_hash: str = ""
    license: str = ""
    created_at: str = Field(
        default_factory=lambda: dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    )
    seed: int | None = None
    parents: list[str] = Field(default_factory=list)
    """Content hashes of the rows this one was derived from. Builds the lineage DAG."""

    notes: str = ""

    @property
    def is_model_generated(self) -> bool:
        return self.source_type == "model_output" and self.generator_model is not None


def content_hash(payload: Any) -> str:
    """Stable content address for a row. Used as a lineage node id."""
    blob = json.dumps(payload, sort_keys=True, default=str, ensure_ascii=False)
    return "sha256:" + hashlib.sha256(blob.encode("utf-8")).hexdigest()[:24]


#: Deterministic stamp for generated rows.
#:
#: A wall-clock ``created_at`` would rewrite every row of the committed task
#: sample on each regeneration, which breaks the byte-identity check and makes
#: a no-op rebuild look like a change. Generated data is reproducible from its
#: seed, so its provenance timestamp is a property of the generator rather than
#: of the moment it ran.
ORACLE_EPOCH = "2026-01-01T00:00:00+00:00"


def oracle_provenance(seed: int, parents: list[str] | None = None) -> Provenance:
    """The provenance every generated task and gold trajectory carries.

    Nothing here came from a model, so nothing here can be poisoned by a
    provider's terms of service. This is what makes the training set legally
    clean by construction rather than by audit.
    """
    return Provenance(
        source_type="oracle_program",
        generator_model=None,
        generator_version="toolsmith/oracle",
        license="MIT",
        created_at=ORACLE_EPOCH,
        seed=seed,
        parents=parents or [],
        notes="Deterministic. Executed in a sandbox, never judged by a model.",
    )
